### ISSUE TITLE
Pthreads impl should barrier at the start?

### ISSUE THREAD

**Issue by jeffhammond** [tactcomplabs/circustent#14]
The OpenMP implementation does a `parallel for`, which synchronizes all threads at the start and finish.

The Pthread implementation contains no synchronization, which means that threads are staggered by the time required for `pthread_create`.  If `pthread_create` is slow, it means that there is less contention than intended, which might impact the quality of results.

I'm not sure if this a problem or not.  Feel free to close.

**Comment by BrodyWilliams** [comment]
Great catch @jeffhammond! I agree with your assessment. Integrating a barrier would be much closer to what was intended. The latest merge should address appropriately. Let us know if you have issues or concerns.
