### ISSUE TITLE
STRIDE-N Kernels and number of iterations

### ISSUE THREAD

**Issue by pbbdasilva** [tactcomplabs/circustent#18]
After some discussion with @BrodyWilliams, we agreed that the number of iterations for the STRIDE-N Kernels for all backends except MPI, OPENSHMEM, and xBGAS are incorrect. If N is the number set by the user to be performed by each thread, the backends are performing  N / stride iterations. Only the 3 mentioned before are performing the correct number of iterations. (Differing from the image that was extracted from the 1st CT paper)

Also, the number of iterations used to calculate the GAMs for each kernel call is still N, not the actual number of iterations
![image](https://user-images.githubusercontent.com/61165929/193622776-1fb93d37-301f-4ebf-82d5-7a45434ee24d.png)

**Comment by jleidel** [comment]
Is the fix for this in PR #19 ?

**Comment by pbbdasilva** [comment]
Yes

**Comment by jleidel** [comment]
Excellent, tracking the PR back to the original issue.

**Comment by jleidel** [comment]
Merged in PR #19
