### ISSUE TITLE
IDX generation using <cstdlib> rand() is not fit for YGM

### ISSUE THREAD

**Issue by prestonpiercey1** [tactcomplabs/circustent#28]
When generating the random index array in CT_YGM::AllocateData, referred to as IDX in the circustent paper, rand() will not suffice for generating the indices. The largest value it can generate is 2147483647.

For a large VAL array, this is a serious problem. All of the indices will be focused at lower ranks and send all of the operations to a few processes at the start of the allocation. 

For example, if we use a VAL memory size parameter of 2000000000 as described in the original paper:

|        The number of indexable uint64_t elements on each rank is:
|        2000000000 / 8 = 250000000. 
|
|        Now, how many 250000000 element arrays can possibly be addressed if we use rand()?
|        Well, if 2147483647 is the largest index we can generate, then we are sending all of our operations to the first 
|        integer_ceiling(2147483647 / 250000000)  = 8.589934588.
|        
| So we are only sending operations to the first **9 ranks**.

Obviously this is a flaw that prevents any productive use of the YGM port. I will get a solution written and pushed before the weekend. 

I apologize for the delay in finding this error, it was only suspected to be a problem after getting scaling data on the flawed implementation.

**Comment by prestonpiercey-tamu** [comment]
Solved by using std::mt19937_64 random number engine with std::uniform_int_distribution to generate values in the IDX array. This will uniformly sample values in the range [0, (pes * elems) - 1] for benchmarks where IDX values should be VAL indices, or values in the range [0, (pes * (iters + 1)) - 1] for the PTRCHASE kernels. IDX is not used by the CENTRAL and STRIDE1/N Kernels

**Comment by prestonpiercey1** [comment]
Solved by using std::mt19937_64 random number engine with std::uniform_int_distribution to generate values in the IDX array. This will uniformly sample values in the range [0, (pes * elems) - 1] for benchmarks where IDX values should be VAL indices, or values in the range [0, (pes * (iters + 1)) - 1] for the PTRCHASE kernels. IDX is not used by the CENTRAL and STRIDE1/N Kernels
