### ISSUE TITLE
verification question

### ISSUE THREAD

**Issue by zjin-lcf** [tactcomplabs/circustent#6]
Do the OpenMP targeting offloading examples verify that the host and device results match ? 

Thanks

**Comment by jleidel** [comment]
@zjin-lcf, not currently, no.  The examples quantify the same data as the base host results.  This can certainly be added though

**Comment by BrodyWilliams** [comment]
@zjin-lcf, just to clarify, are you referring to verification that the randomized data that is transferred to the target mirrors that which was originally on the target? The benchmark kernels themselves are performed only on the target and not the host.

**Comment by zjin-lcf** [comment]
I didn't realize my question is not clear. 

Does the result of vector add on a host matches the result of vector add on a device ?  I understand the results on a device are not verified currently.

**Comment by jleidel** [comment]
@zjin-lcf, not necessarily.  It depends upon a number of factors.  First, the test inputs are generated randomly, so the distribution and indices will be different between runs and between whether you run it on the host or a target device.  Second, the memory subsystems of hosts and devices will almost certainly be different.  If a host device has a strongly ordered memory system and a device has a weakly ordered memory system, then the results for certain pathological kernels may be slightly different.  The goal here is not to _verify_ consistency between different devices.  The goal here is to quantitatively analyze the effect of massive bulk atomic memory ops on a given architecture.  Think of CircusTent as being analogous to McCalpin's STREAM benchmark using atomics.  Does that help?

**Comment by zjin-lcf** [comment]
Yes. Thanks for your explanation.
