### ISSUE TITLE
MPI runs crash with RMA errors

### ISSUE THREAD

**Issue by tonycurtis** [tactcomplabs/circustent#8]
Tested with both MVAPICH and Open-MPI.  Here's a sample Open-MPI (4.0.5 / 4.1.0) outcome:

```
$ ./circustent -p 4 -i 100 -m $((1024 * 1024))  -b RAND_ADD
Initializing MPI data members
Done initializing MPI data members
Beginning test execution
[fj-debug2:18252] *** An error occurred in MPI_Get
[fj-debug2:18252] *** reported by process [3340632065,281470681743360]
[fj-debug2:18252] *** on win ucx window 4
[fj-debug2:18252] *** MPI_ERR_RMA_SYNC: error executing rma sync
[fj-debug2:18252] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[fj-debug2:18252] ***    and potentially your MPI job)
```

**Comment by jleidel** [comment]
@BrodyWilliams , can you help triage?

**Comment by BrodyWilliams** [comment]
@jleidel: Sure thing, I will take a look this afternoon. Apparently I need to check some notification setting, I was not even aware there were open issues.

**Comment by tonycurtis** [comment]
How does the MPI launch work?  I can't find mpirun/exec anywhere in the code...am I missing something obvious?

**Comment by BrodyWilliams** [comment]
The mpirun command is used when starting the program. We should probably update the documentation to that effect. However, there seems to be some other issues. I am looking into them now.

**Comment by tonycurtis** [comment]
So

```
mpiexec -n NP ./circustent -pes NP -b ...
```

?  Seems strange to have to repeat the `-pes` parameter.

**Comment by BrodyWilliams** [comment]
It seem there was at least two issues. One was related to how the displacement in the RMA calls is calculated for dynamic windows and the other was missing fences. I have push an "Issue_8" branch that hopefully fixes these problems. Can you test and see if it resolves the problem?

<img width="1164" alt="Screen Shot 2021-03-09 at 6 25 50 PM" src="https://user-images.githubusercontent.com/36043827/110557090-7a344e80-8105-11eb-8505-34c937adfcf0.png">

For the PEs argument, I agree. We should look into changing this for the MPI and SHMEM implementations.

**Comment by tonycurtis** [comment]
Yeah, that looks good

**Comment by BrodyWilliams** [comment]
Great, I will let @jleidel review and merge the changes then.
